# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e6644cfdbbfbf2e9dca41d9dc46b0ed7cbf6a6d15ec27ae636a3b813b0a9dc36efc40893187d63e115966ab93421f1eab4f15768efa64b1534b87f48c7f9b2b

test:
  secret_key_base: 9d4adc28bccdcbc2e8a6771f55fccd152eb4d3bc7acff70607cd7ac9a23b97e39611956bd47878515dc00d3b4523d60fb28a3999e30a3b6739d0a7a4ad3dd3ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
